server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: local
  cloud:
    gateway:
      # Updated configuration keys for Spring Cloud Gateway 2025.0.0
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - name: Retry
          args:
            retries: 3
            methods: GET,POST,PUT,DELETE
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10  # requests per second
              burstCapacity: 20  # maximum requests in burst
        - name: CircuitBreaker
          args:
            name: default-circuit-breaker
            fallbackUri: forward:/fallback
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false

  # Redis Configuration (for rate limiting)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# JWT Configuration
jwt:
  secret: "myVerySecureSecretKeyForJWTTokenGeneration123456789"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
    # Updated gateway endpoint configuration
    gateway:
      access: unrestricted

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.amponsem.api_gateway: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"