server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: api-gateway
    prefer-ip-address: false

spring.data.redis:
  host: redis
  port: 6379

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO